server:
  port: 10010
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zxtan-github/config-server.git
          searchPaths: config
  application:
    name: spring-config

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/